---
abstract: 'Ensure that tests needing a display have one'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::NeedsDisplay
name: Test-NeedsDisplay
no_index:
  directory:
    - inc
    - t
requires:
  File::Spec: 0.80
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.04
