
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.55
distribution_type: module
version: 0.02
name: Test-NeedsDisplay
author: Adam Kennedy <cpan@ali.as>, L<http://ali.as/>
license: perl
build_requires: 
  Test::More: 0.47
requires: 
  perl: 5.6.0
  File::Spec: 0.80
abstract: Ensure that tests needing a display have one
