name: Test-NeedsDisplay
version: 0.01
abstract: Ensure that tests needing a display have one
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
requires:
  perl: 5.6.0
  File::Spec: 0.80
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
